#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

################################################################################
# . ${R}etc/init.d/rc.vtol_defaults
#
# VTOL default parameters.
#
# NOTE: Script variables are declared/initialized/unset in the rcS script.
#

set VEHICLE_TYPE vtol

# MAV_TYPE_VTOL_FIXEDROTOR 22
param set-default MAV_TYPE 22

# there is a 2.5 factor applied on COM_POS_FS_EPH if for invalidation
param set-default COM_POS_FS_EPH 50

param set-default COM_POS_LOW_EPH 50

param set-default MIS_TAKEOFF_ALT 20
param set-default MIS_YAW_TMT 10

param set-default EKF2_ARSP_THR 10
param set-default EKF2_FUSE_BETA 1

param set-default HTE_VXY_THR 2

param set-default MIS_TKO_LAND_REQ 2

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_VEL_MANUAL 5
param set-default MPC_XY_ERR_MAX 5
param set-default MPC_XY_VEL_MAX 8
param set-default MPC_JERK_MAX 4.5
param set-default MPC_YAW_MODE 4

# reduce aggressiveness around roll and yaw axis,
# as VTOLs usually have high intertia and lot af drag due to wings
param set-default MC_ROLL_P 5
param set-default MC_ROLLRATE_MAX 120
param set-default MC_YAW_P 2
param set-default MC_YAWRATE_MAX 120
param set-default MPC_MAN_Y_MAX 90

param set-default RTL_TYPE 1

param set-default SYS_HAS_NUM_ASPD 1 # by default require an airspeed sensor

param set-default WV_EN 1

################################################################################

# Original airframe

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=standard_vtol}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_ARSPDSIM 1

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2

param set-default COM_PREARM_MODE 2

param set-default CA_ROTOR_COUNT 5
param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AZ 0
param set-default CA_ROTOR4_PX 0.2

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 1500
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 10
param set-default SIM_GZ_EC_MAX4 1500

param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 3500

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203

param set-default COM_RC_IN_MODE 1

param set-default CA_SV_CS_COUNT 3
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1

param set-default NPFG_PERIOD 12
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

param set-default MC_AIRMODE 1
param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5
param set-default NAV_DLL_ACT 2

param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 0.3
param set-default VT_TYPE 2
param set-default FD_ESCS_EN 0

################################################################################

# AAS Custom

# Simulated sensors
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default COM_RCL_EXCEPT 7 # Disable RC loss action
param set-default UXRCE_DDS_SYNCT 0 # This lets PX4 SITL keep using Gazebo simulation time
param set-default MPC_XY_CRUISE 3.0 # Limit the VTOL's multicopter mode position controller speed

# Configure "Hold" behaviour
param set-default NAV_LOITER_RAD 500 # Default radius for Hold mode and MAV_CMD_DO_REPOSITION
param set-default VTO_LOITER_ALT 150 # Altitude relative to home at which vehicle will loiter in Hold mode

# Configure "Offboard" failsafe behaviour
param set-default COM_QC_ACT -1 # No quadchute, FUN BUT DO NOT USE IN REAL LIFE
param set-default COM_OBL_RC_ACT 5 # Force hold mode when falling out of offboard
param set-default COM_OF_LOSS_T 1.0 # Timeout for the offboard failsafe to kick in
param set-default NAV_RCL_ACT 1 # RC loss failsafe mode: hold mode
param set-default COM_RC_OVERRIDE 1 # Enable RC stick override of auto (0) and/or offboard modes (1)

# Increase the transition throttle
param set-default VT_F_TRANS_THR 1

# Increase max and cruise airspeed
param set-default FW_AIRSPD_MAX 25.0
param set-default FW_AIRSPD_TRIM 18.0

# Increase timeouts/rates for faster-than-real-life simulation
param set-default COM_RC_LOSS_T 35
param set-default COM_DL_LOSS_T 300
