name: cleanup packages

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch: {}

jobs:
  delete-old-versions:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: Prune images older than 10 days (except latest)
        uses: snok/container-retention-policy@v3
        with:
          image-names: |
            aircraft-image
            ground-image
            simulation-image
          cut-off: 10d
          image-tags: "!latest"
          keep-n-most-recent:: 1
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
